services:
  dynamodb-local:
    image: amazon/dynamodb-local:2.5.2
    container_name: iamspeed-dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -inMemory"
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/8000'"]
      interval: 5s
      timeout: 3s
      retries: 5
